### ISSUE TITLE
Step-02 Not Working. Start Button does not get the video strem

### ISSUE THREAD

**Issue by RosarioAleCali** [googlecodelabs/webrtc-web#22] opened 2017-05-22 15:13 UTC
Hello Everyone!
I simply want to start by saying that I am new to this technology and that today is my first day using it so I am not very fluent with the the proper terminology.

My problem is simple, yet very strange!
When I click on "Start" the browser takes a while to load the stream and the I get a black window.
Then, when clicking on "Call" nothing happens but when I click "Hang Up" then I get two black windows.

So, I am not sure what info I should give you to fix this problem but I will start by saying that I am using Google Chrome 58 on Ubuntu 16.04 and step-01 worked flawless even when adding the effects.
I will provide more informations and logs as requested.
I am also providing a console log of everything that happens from "Start" to "Hang Up".
[log.txt](https://github.com/googlecodelabs/webrtc-web/files/1019288/log.txt)

**Comment by nitobuendia** [comment] 2017-11-28 15:34
@RosarioAleCali 
I do not see anything wrong in your logs; except that the video generated is 2x2px instead of a normal size. For comparison, mine is 640x480px.

I thought this could be related to permissions on the camera; however, when denied permissions for camera, an error / alert is thrown.

Is this still reproducible? Also, are you able to use your camera on other apps ([you can test any here](https://www.google.com/search?q=test+camera)).

Thank you!

**Comment by samdutton** [comment] 2017-12-11 13:47
Thanks @RosarioAleCali, and apologies for the delay in responding. 

I'm going to close this, because there hasn't been a response to @nitobuendia, but feel free to re-open if necessary.

**Closed by samdutton** 2017-12-11 13:47 UTC
