### ISSUE TITLE
STEP 7

### ISSUE THREAD

**Issue by muhammadbilal92** [googlecodelabs/webrtc-web#36] opened 2017-07-26 07:10 UTC
hello everyone! i am new here.
i have followed all the steps mentioned.  
i downloaded node.js from the node.org updated it to its latest version. i also installed the npm packager too. but it did not show me the bash dialog box. 
after that after creating the index.js file in the work directory, i gave the "node index.js" command but it gave me the following error 

Error: Cannot find module 'socket.io'     
at Function.Module._resolveFilename (module.js:469:15)             
at Function.Module._load (module.js:417:25)                        
at Module.require (module.js:497:17)                               
at require (internal/module.js:20:19)                               
at Object.<anonymous> (C:\Users\Bilal\Desktop\work\index.js:6:16)    
at Module._compile (module.js:570:32)                               
 at Object.Module._extensions..js (module.js:579:10)                 
 at Module.load (module.js:487:32)                                  
  at tryModuleLoad (module.js:446:12)                                 
 at Function.Module._load (module.js:438:3)                                                                                             

Also i am having trouble in loading the localhost:8080 

kindly help me with this. thanks in advance

**Comment by nitobuendia** [comment] 2017-11-28 15:11
Hello @muhammadbilal92,

With step 7, you mean step 7 in the codelab, which is actually step 5 on the code; right?

Unfortunately, I am unable to reproduce.
Could you confirm that:
1. This is still reproducible
2. You run npm install from terminal on the folder where index.js is before running node index.js

Thank you!

**Comment by samdutton** [comment] 2017-12-13 14:03
Hi @muhammadbilal92 — thanks for filling an issue and apologies for the delay in responding.

I'll close the issue now, but feel free to open again if you're still experiencing problems.

**Closed by samdutton** 2017-12-13 14:03 UTC
