### ISSUE TITLE
Not correctly checking number of clients in room (step-04)

### ISSUE THREAD

**Issue by AlexRobinson-** [googlecodelabs/webrtc-web#5] opened 2016-09-02 15:47 UTC
In step-04/index.js the server checks how many clients are in the room by calling

``` js
var numClients = io.sockets.sockets.length;
log('Room ' + room + ' now has ' + numClients + ' client(s)');
```

However this returns undefined, as well as doesn't actually try and check for the given room.

A proposed fix:

``` js
var clientsInRoom = io.nsps['/'].adapter.rooms[room];
var numClients = clientsInRoom === undefined ? 0 : Object.keys(clientsInRoom).length;
```

Or if you also want to upgrade to socket v1.4

``` js
var clientsInRoom = io.nsps['/'].adapter.rooms[room];
var numClients = clientsInRoom === undefined ? 0 : Object.keys(clientsInRoom.sockets).length;
```

A full fix _\+ some small cleans up :)_ would look like

``` js
var clientsInRoom = io.nsps['/'].adapter.rooms[room];
var numClients = clientsInRoom === undefined ? 0 : Object.keys(clientsInRoom).
// socket.io 1.4.8
var numClients = clientsInRoom === undefined ? 0 : Object.keys(clientsInRoom.sockets).length;

// max two clients
if (numClients === 2) {
  socket.emit('full', room);
  return;
}

log('Room ' + room + ' now has ' + (numClients + 1) + ' client(s)');

if (numClients === 0) {
  socket.join(room);
  log('Client ID ' + socket.id + ' created room ' + room);
  socket.emit('created', room, socket.id);

} else {
  log('Client ID ' + socket.id + ' joined room ' + room);
  io.sockets.in(room).emit('join', room);
  socket.join(room);
  socket.emit('joined', room, socket.id);
  io.sockets.in(room).emit('ready');
}
```

See: https://github.com/AlexRobinson-/webrtc-web/blob/fix-check-room-clients/step-04/index.js

**Comment by samdutton** [comment] 2017-02-14 18:16
Hi @AlexRobinson-

Thanks very much for this — apologies for the delay in responding. 

Do you want to do a PR for this? No worries if you don't have time, I'll have a go myself.

**Comment by aaronang** [comment] 2017-02-14 18:17
@samdutton I can also take up this task.

**Comment by samdutton** [comment] 2017-02-14 18:18
@aaronang go for it!

**Comment by visrey** [comment] 2017-10-10 19:32
After struggling for a day I saw this

**Comment by Dealerpriest** [comment] 2018-01-22 14:42
This issue is still relevant. I guess it is not merged to the master branch?

**Comment by nitobuendia** [comment] 2018-01-23 13:21
@Dealerpriest Thanks a lot for pointing it out. If I recall correctly, the fix was not merged because it did not fully solve the issue. However, we will test again and request changes or send a PR based on that. No ETA, but we will try to prioritise it soon.

**Comment by nitobuendia** [comment] 2018-01-23 14:59
I have added a few console.log* on step-4 to see what is happening here before jumping into the PR.

* no judging, please, it was a quick dirty solution :)

```
    console.log('io.sockets.sockets', io.sockets.sockets);
    console.log('io.sockets.sockets.length', io.sockets.sockets.length);
```

On joining first time:
```
io.sockets.sockets {
  K_cbkZqQaWrpz66cAAAC: Socket {}
}
io.sockets.sockets.length undefined
```

This already pinpoints the issue on #13 and here.

On adding a new peer to the same room:
```
io.sockets.sockets {
  K_cbkZqQaWrpz66cAAAC: Socket {},
  'W-72ivSmDZOPxPaiAAAD':  Socket {}
}
io.sockets.sockets.length undefined
```

Until here Object.keys(io.sockets.sockets) do seem as a valid solution.

On adding a new peer to a new room:
```
io.sockets.sockets {
  K_cbkZqQaWrpz66cAAAC: Socket {},
  'W-72ivSmDZOPxPaiAAAD': Socket {},
  jQtR9RwnbGhrhae5AAAE: Socket {}
}
```

Here, that solution seems to break. Either the rooms are not working properly, or Object.keys() would simply count all the sockets available. In this case, it will return 3 when it should be 2 for room A, and 1 for room B (names are chosen by me).


First socket seem to contain room information:
`rooms: { K_cbkZqQaWrpz66cAAAC: 'K_cbkZqQaWrpz66cAAAC', a: 'a' },`
But not so much its peer on the same room:
`rooms: { 'W-72ivSmDZOPxPaiAAAD': 'W-72ivSmDZOPxPaiAAAD' },`

This seems to change after connection is made; but this was already after the third connection, so it should not be the case.

Testing a bit now with the proper Debugger in Node.js and Chrome Dev Tools.

**Comment by nitobuendia** [comment] 2018-01-23 15:38
To add a last piece to the former.

On `socket.on('create or join', function(room) {});`
socket.rooms does not seem to update properly and fast enough when a peer joins.

Join 3 times same room T:
<img width="778" alt="screen shot 2018-01-23 at 23 30 27" src="https://user-images.githubusercontent.com/16522489/35284488-eb5ad618-0095-11e8-980f-d4fa4fc7aaf0.png">

Join room X, join room F, join again room X:
<img width="777" alt="screen shot 2018-01-23 at 23 31 34" src="https://user-images.githubusercontent.com/16522489/35284532-066f087a-0096-11e8-92bc-d5a3ced7649a.png">

Join room Y, join again room Y, join room G:
<img width="773" alt="screen shot 2018-01-23 at 23 36 26" src="https://user-images.githubusercontent.com/16522489/35284646-4c5e2fa0-0096-11e8-8f66-27672ce1d43c.png">



These tests were done using io.sockets.sockets.rooms to follow current situation.
Proposed solution on #15 uses io.sockets.adapter.rooms. Checking that next.

**Comment by nitobuendia** [comment] 2018-01-23 15:52
Similar tests:

Join roomD 3 times:
<img width="763" alt="screen shot 2018-01-23 at 23 47 09" src="https://user-images.githubusercontent.com/16522489/35285377-2dbb9572-0098-11e8-9c10-24aca6c1d3ff.png">

Join room E, join room C, join room E again:
<img width="777" alt="screen shot 2018-01-23 at 23 49 11" src="https://user-images.githubusercontent.com/16522489/35285403-43ec00a2-0098-11e8-90f3-3d0e981a7842.png">

Length and peers is always 1. At this stage I wondered whether I was not making the connection at all, but client-side console actually was changing the numbers:
<img width="357" alt="screen shot 2018-01-23 at 23 51 54" src="https://user-images.githubusercontent.com/16522489/35285470-6bb0aab6-0098-11e8-8131-91e2e49cf654.png">

I will research a bit more on how socket.io handles the room connections. Not super familiar with it at the moment.

**Comment by nitobuendia** [comment] 2018-01-25 11:51
# Testing Environment
Upgraded to socket.io 2.0.4
Testing replacing the current set up of numClients for this one:

```
   const numClientsData = [
      {
        solution: '#5 proposal',
        implementation: 'Object.keys(io.nsps["/"].adapter.rooms[room]).length',
        numClients: Object.keys(io.nsps["/"].adapter.rooms[room] || {}).length,
      },
      {
        solution: '#13 proposal',
        implementation: 'Object.keys(io.sockets.sockets).length',
        numClients: Object.keys(io.sockets.sockets).length,
      },
      {
        solution: '#15 proposal',
        implementation: 'Object.keys(io.sockets.adapter.rooms[room]).length',
        numClients: Object.keys(io.sockets.adapter.rooms[room] || {}).length,
      },
      {
        solution: 'stackoverflow A',
        implementation: 'Object.keys(io.sockets.clients().sockets).length',
        numClients: Object.keys(io.sockets.clients().sockets).length,
      },
      /*
      {
        solution: 'stackoverflow A - variant 2',
        implementation: 'Object.keys(io.sockets.clients(room)).length',
        numClients: Object.keys(io.sockets.clients(room) || {}).length,
      },
      */
      {
        solution: 'stackoverflow B',
        implementation: 'Object.keys(io.sockets.connected).length',
        numClients: Object.keys(io.sockets.connected).length,
      }
    ];

    for (const solution of numClientsData) {
      log(
        `There are ${solution.numClients} clients connected in room ${room}. ` +
        `According to ${solution.solution}; ` +
        `implemented as ${solution.implementation}.`);
    }
```
# Testing Results
I will add check marks for correct or incorrect [✖✓] and I will do according to whether we are considering before or after joining (first check mark is before; second check mark is after).

**First peer joins room test:**
Message from client: Asking to join room test
Message from server: Received request to create or join room test
- [✓] [✖] Message from server: There are 0 clients connected in room test. According to #5 proposal; implemented as Object.keys(io.nsps["/"].adapter.rooms[room]).length.
- [✖] [✓] Message from server: There are 1 clients connected in room test. According to #13 proposal; implemented as Object.keys(io.sockets.sockets).length.
- [✓] [✖] Message from server: There are 0 clients connected in room test. According to #15 proposal; implemented as Object.keys(io.sockets.adapter.rooms[room]).length.
- [✖] [✓] Message from server: There are 1 clients connected in room test. According to stackoverflow A; implemented as Object.keys(io.sockets.clients().sockets).length.
- [✖] [✓] Message from server: There are 1 clients connected in room test. According to stackoverflow B; implemented as Object.keys(io.sockets.connected).length.

Message from server: Client ID uRIzg0u2zRGHgLYhAAAB created room test

**Second peer joins the room test**
Message from client: Asking to join room test
Message from server: Received request to create or join room test

- [✖][✓] Message from server: There are 2 clients connected in room test. According to #5 proposal; implemented as Object.keys(io.nsps["/"].adapter.rooms[room]).length.
- [✖][✓] Message from server: There are 2 clients connected in room test. According to #13 proposal; implemented as Object.keys(io.sockets.sockets).length.
- [✖][✓] Message from server: There are 2 clients connected in room test. According to #15 proposal; implemented as Object.keys(io.sockets.adapter.rooms[room]).length.
- [✖][✓] Message from server: There are 2 clients connected in room test. According to stackoverflow A; implemented as Object.keys(io.sockets.clients().sockets).length.
- [✖][✓] Message from server: There are 2 clients connected in room test. According to stackoverflow B; implemented as Object.keys(io.sockets.connected).length.

Message from client: Room test is full :^(


**Third peer joins the room test**
_note that at this point the room is full and no new peer should have joined_

Message from client: Asking to join room test
Message from server: Received request to create or join room test

- [✓][?] Message from server: There are 2 clients connected in room test. According to #5 proposal; implemented as Object.keys(io.nsps["/"].adapter.rooms[room]).length.
- [✖][?] Message from server: There are 3 clients connected in room test. According to #13 proposal; implemented as Object.keys(io.sockets.sockets).length.
- [✓][?] Message from server: There are 2 clients connected in room test. According to #15 proposal; implemented as Object.keys(io.sockets.adapter.rooms[room]).length.
- [✖][?] Message from server: There are 3 clients connected in room test. According to stackoverflow A; implemented as Object.keys(io.sockets.clients().sockets).length.
- [✖][?] Message from server: There are 3 clients connected in room test. According to stackoverflow B; implemented as Object.keys(io.sockets.connected).length.

Message from client: Room test is full :^(


**Fourth peer join rooms test**
_note that at this point the room is full and no new peer should have joinned_

Message from client: Asking to join room test
Message from server: Received request to create or join room test

- [?][?] Message from server: There are 2 clients connected in room test. According to #5 proposal; implemented as Object.keys(io.nsps["/"].adapter.rooms[room]).length.
- [✖][?] Message from server: There are 4 clients connected in room test. According to #13 proposal; implemented as Object.keys(io.sockets.sockets).length.
- [?][?] Message from server: There are 2 clients connected in room test. According to #15 proposal; implemented as Object.keys(io.sockets.adapter.rooms[room]).length.
- [✖][?] Message from server: There are 4 clients connected in room test. According to stackoverflow A; implemented as Object.keys(io.sockets.clients().sockets).length.
- [✖][?] Message from server: There are 4 clients connected in room test. According to stackoverflow B; implemented as Object.keys(io.sockets.connected).length.

Message from client: Room test is full :^(



# Summary of Results

## Table of results

- Peers in room: [0->1, 1->2, 2->2|3, 2->2|3->4]
- Proposal #5 [0, 2, 2, 2]
- Proposal #13 [1, 2, 3, 4]
- Proposal #15 [0, 2, 2, 2]
- Proposal StackOverflow A: [1, 2, 3, 4]
- Proposal StackOverflow B: [1, 2, 3, 4]


## Table of success
_Note that, code-wise, this happens before deciding if the peer joins or not._

If we are considering the check **before peer joins**:

- Proposal #5 [✓, ✖, ✓, ?]
- Proposal #13 [✖, ✖, ✖, ✖]
- Proposal #15 [✓, ✖, ✓, ?]
- Proposal StackOverflow A: [✖, ✖, ✖, ✖]
- Proposal StackOverflow B: [✖, ✖, ✖, ✖]

None of the solutions seems to have performed on point :)

If we are considering the check **after peer joins**:

- Proposal #5 [✖, ✓, ?, ?]
- Proposal #13 [✓, ✓, ?, ?]
- Proposal #15 [✖, ✓, ?, ?]
- Proposal StackOverflow A: [✓, ✓, ?, ?]
- Proposal StackOverflow B: [✓, ✓, ?, ?]

Solutions #13, A and B seems to have worked under this scenario.
However, it is most likely because they counted the number of the peers rather than the numbers of peers on the room. This will lead to the next test where I will add several peers to several rooms.

**Comment by nitobuendia** [comment] 2018-01-25 12:12
# Testing environment
Upgraded socket.io to 2.0.4.

Simplified room joining logic to avoid limitation per room:
```
    if (numClients === 0) {
      socket.join(room);
      log('Client ID ' + socket.id + ' created room ' + room);
      socket.emit('created', room, socket.id);

    } else (numClients === 1) {
      log('Client ID ' + socket.id + ' joined room ' + room);
      io.sockets.in(room).emit('join', room);
      socket.join(room);
      socket.emit('joined', room, socket.id);
      io.sockets.in(room).emit('ready');
    }
```

Logging data same as previous:
 ```
 const numClientsData = [
      {
        solution: '#5 proposal',
        implementation: 'Object.keys(io.nsps["/"].adapter.rooms[room]).length',
        numClients: Object.keys(io.nsps["/"].adapter.rooms[room] || {}).length,
      },
      {
        solution: '#13 proposal',
        implementation: 'Object.keys(io.sockets.sockets).length',
        numClients: Object.keys(io.sockets.sockets).length,
      },
      {
        solution: '#15 proposal',
        implementation: 'Object.keys(io.sockets.adapter.rooms[room]).length',
        numClients: Object.keys(io.sockets.adapter.rooms[room] || {}).length,
      },
      {
        solution: 'stackoverflow A',
        implementation: 'Object.keys(io.sockets.clients().sockets).length',
        numClients: Object.keys(io.sockets.clients().sockets).length,
      },
      /*
      {
        solution: 'stackoverflow A - variant 2',
        implementation: 'Object.keys(io.sockets.clients(room)).length',
        numClients: Object.keys(io.sockets.clients(room) || {}).length,
      },
      */
      {
        solution: 'stackoverflow B',
        implementation: 'Object.keys(io.sockets.connected).length',
        numClients: Object.keys(io.sockets.connected).length,
      }
    ];

    for (const solution of numClientsData) {
      log(
        `There are ${solution.numClients} clients connected in room ${room}. ` +
        `According to ${solution.solution}; ` +
        `implemented as ${solution.implementation}.`);
    }
```

# Testing results

This time we will join room A x3, then join room B x3.

**Peer 1 joins A:**
Message from client: Asking to join room A
Message from server: Received request to create or join room A

- Message from server: There are 0 clients connected in room A. According to #5 proposal; implemented as Object.keys(io.nsps["/"].adapter.rooms[room]).length.
- Message from server: There are 1 clients connected in room A. According to #13 proposal; implemented as Object.keys(io.sockets.sockets).length.
- Message from server: There are 0 clients connected in room A. According to #15 proposal; implemented as Object.keys(io.sockets.adapter.rooms[room]).length.
- Message from server: There are 1 clients connected in room A. According to stackoverflow A; implemented as Object.keys(io.sockets.clients().sockets).length.
- Message from server: There are 1 clients connected in room A. According to stackoverflow B; implemented as Object.keys(io.sockets.connected).length.

Message from server: Client ID o6gbjdVEFihD9Q9ZAAAA created room A

**Peer 2 joins A**
Message from client: Asking to join room A
Message from server: Received request to create or join room A

- Message from server: There are 2 clients connected in room A. According to #5 proposal; implemented as Object.keys(io.nsps["/"].adapter.rooms[room]).length.
- Message from server: There are 2 clients connected in room A. According to #13 proposal; implemented as Object.keys(io.sockets.sockets).length.
- Message from server: There are 2 clients connected in room A. According to #15 proposal; implemented as Object.keys(io.sockets.adapter.rooms[room]).length.
- Message from server: There are 2 clients connected in room A. According to stackoverflow A; implemented as Object.keys(io.sockets.clients().sockets).length.
- Message from server: There are 2 clients connected in room A. According to stackoverflow B; implemented as Object.keys(io.sockets.connected).length.

Message from client: Room A is full :^(

**Peer 3 joins A**
Message from client: Asking to join room A
Message from server: Received request to create or join room A

- Message from server: There are 2 clients connected in room A. According to #5 proposal; implemented as Object.keys(io.nsps["/"].adapter.rooms[room]).length.
- Message from server: There are 3 clients connected in room A. According to #13 proposal; implemented as Object.keys(io.sockets.sockets).length.
- Message from server: There are 2 clients connected in room A. According to #15 proposal; implemented as Object.keys(io.sockets.adapter.rooms[room]).length.
- Message from server: There are 3 clients connected in room A. According to stackoverflow A; implemented as Object.keys(io.sockets.clients().sockets).length.
- Message from server: There are 3 clients connected in room A. According to stackoverflow B; implemented as Object.keys(io.sockets.connected).length.

Message from client: Room A is full :^(


**Peer 4 joins B (1)**
Message from client: Asking to join room B
Message from server: Received request to create or join room B

- Message from server: There are 0 clients connected in room B. According to #5 proposal; implemented as Object.keys(io.nsps["/"].adapter.rooms[room]).length.
- Message from server: There are 4 clients connected in room B. According to #13 proposal; implemented as Object.keys(io.sockets.sockets).length.
- Message from server: There are 0 clients connected in room B. According to #15 proposal; implemented as Object.keys(io.sockets.adapter.rooms[room]).length.
- Message from server: There are 4 clients connected in room B. According to stackoverflow A; implemented as Object.keys(io.sockets.clients().sockets).length.
- Message from server: There are 4 clients connected in room B. According to stackoverflow B; implemented as Object.keys(io.sockets.connected).length.

Message from server: Client ID ifNbqNrJNjOrv3w0AAAD created room B

**Peer 5 joins B (2)**
Message from client: Asking to join room B
Message from server: Received request to create or join room B

- Message from server: There are 2 clients connected in room B. According to #5 proposal; implemented as Object.keys(io.nsps["/"].adapter.rooms[room]).length.
- Message from server: There are 5 clients connected in room B. According to #13 proposal; implemented as Object.keys(io.sockets.sockets).length.
- Message from server: There are 2 clients connected in room B. According to #15 proposal; implemented as Object.keys(io.sockets.adapter.rooms[room]).length.
- Message from server: There are 5 clients connected in room B. According to stackoverflow A; implemented as Object.keys(io.sockets.clients().sockets).length.
- Message from server: There are 5 clients connected in room B. According to stackoverflow B; implemented as Object.keys(io.sockets.connected).length.

Message from client: Room B is full :^(


**Peer 6 joins B (3)**
Message from client: Asking to join room B
Message from server: Received request to create or join room B

- Message from server: There are 2 clients connected in room B. According to #5 proposal; implemented as Object.keys(io.nsps["/"].adapter.rooms[room]).length.
- Message from server: There are 6 clients connected in room B. According to #13 proposal; implemented as Object.keys(io.sockets.sockets).length.
- Message from server: There are 2 clients connected in room B. According to #15 proposal; implemented as Object.keys(io.sockets.adapter.rooms[room]).length.
- Message from server: There are 6 clients connected in room B. According to stackoverflow A; implemented as Object.keys(io.sockets.clients().sockets).length.
- Message from server: There are 6 clients connected in room B. According to stackoverflow B; implemented as Object.keys(io.sockets.connected).length.

Message from client: Room B is full :^(


# Summary of Results

## Observations
We can clearly see that proposal #13, and both StackOverflow proposal are simply counting the number of connected peers and not per room. Hence, why they were mainly accurate a posteriori on the first check.

For the rest, they tend to go from 0 (when no one is connected) to 2 (when second peer ASKS to join); regardless of whether it's the second or third peer. Hence, they do not seem to be solving the issue either.

## Additional non-test observations
When the rooms, they always show only one peer which is the peer which created the room.

When verifying the peers, they always have one room (themselves) or two but only if they have created the room; if not, the room does not get added.

## Conclusions
Unless I am missing something, something is buggy here. Either:
(a) The peers are not connecting properly to rooms due to faulty logic.
- or -
(b) Socket.io is not assigning the peers successfully to the rooms.

## Potential next steps

Write a simplified version of this code with peers joining rooms. Verify output there.

If still buggy: raise it to socket.io. If fixed: good. If not fixed: consider alternatives.
If not buggy, review our code again to see if there's any issue with the connection.




// For all: if someone wants to reproduce these results under different environments and confirm or counter-argue these findings, it would be great :)
// cc @samdutton

**Comment by katastreet** [comment] 2018-01-28 12:58
```
`var clientsInRoom = io.sockets.adapter.rooms[room];
    var numClients = clientsInRoom ?Object.keys(clientsInRoom.sockets).length : 0;
    log('Room ' + room + ' now has ' + numClients + ' client(s)');

    if (numClients === 0) {
      socket.join(room);
      log('Client ID ' + socket.id + ' created room ' + room);
      socket.emit('created', room, socket.id);
  } else if (numClients === 1) {
      log('Client ID ' + socket.id + ' joined room ' + room);
      io.sockets.in(room).emit('join', room);
      socket.join(room);
      socket.emit('joined', room, socket.id);
      io.sockets.in(room).emit('ready');
    } else { // max two clients
      socket.emit('full', room);
    }`
```
this solved the problem for me

**Comment by nitobuendia** [comment] 2018-01-29 11:22
@katastreet That solution is equivalent to the proposed in #15 and my tests say it does not work.

It starts with 0 and then moves to 2 when each of the two first peers join; either it should return 0, 1 (before joining) or 1,2 (after joining); probably the former.

In addition, it seems to get stuck at 2.


Could kindly you remove the two peers limit and test these scenarios:

- First peer joins room A (should count 0).
- Second peer joins room A (should count 1).
- Third peer joins room A (should count 2).
- Fourth peer joins room B (should count 0).
- Fifth peer joins room B (should count 1).

_Alternatively, all can be +1 and could work._ Could you kindly confirm?



To remove the max numbers of peers, you can change the if statements for:

```
    if (numClients === 0) {
      socket.join(room);
      log('Client ID ' + socket.id + ' created room ' + room);
      socket.emit('created', room, socket.id);
  } else {
      log('Client ID ' + socket.id + ' joined room ' + room);
      io.sockets.in(room).emit('join', room);
      socket.join(room);
      socket.emit('joined', room, socket.id);
      io.sockets.in(room).emit('ready');
    }
```


Thank you so much!

**Comment by katastreet** [comment] 2018-01-30 04:21
@nitobuendia 
you are counting by doing in  #15 :
`Object.keys(io.sockets.adapter.rooms[room] || {}).length,`

But have you noticed, what i am doing is:
```
var clientsInRoom = io.sockets.adapter.rooms[room];
var numClients = clientsInRoom ?Object.keys(clientsInRoom.sockets).length : 0;
```
which is equivalent to 
`Object.keys(io.sockets.adapter.rooms[room].sockets).length`
only if `io.sockets.adapter.rooms[room]` exists

And as per the tests that you are telling me, its all working fine.
First peer joins room A (is count 0).
Second peer joins room A (is count 1).
Third peer joins room A (is count 2). _So cannot connect_
fourth peer joins room A(is count [0)]

also you can see yourself with with node.js signaling server [link](https://github.com/katastreet/webrtcchat/blob/master/index.js)

**Comment by nitobuendia** [comment] 2018-01-30 23:43
@katastreet Thanks a lot for the follow up there :)

From the original code I used:
This piece: `io.sockets.adapter.rooms[room] || {}``
Use io.sockets.adapter.rooms[room] only if io.sockets.adapter.rooms[room] exists.
Otherwise, use an empty object (whose key length will be 0).
Hence, that logic is equivalent.


The only difference between your version is that you count the length of the key of the sockets, which is what we were doing in proposal #13, but not #15. Hence, testing it.

Nonetheless, I also encountered that the if-else on my tests were buggy. Hence, running them again together with yours and will post the results soon.

**Comment by nitobuendia** [comment] 2018-01-30 23:55
@katastreet Your solution seems to work perfectly. Thanks a lot :)
It counts a priori and scales from 0 to n-1 where n is the peer which is joining the room now.
I am sending a PR now if you are fine with it.

For the record, the solution is similar to the one @AlexRobinson proposed, without using the namespace. Probably, the main issue on the test here is that we used the first fix, but while upgrading to sockets.io 1.4.

// cc @samdutton

**Comment by nitobuendia** [comment] 2018-02-05 08:59
@samdutton This is fixed by #65

**Comment by samdutton** [comment] 2018-02-05 10:15
@katastreet @AlexRobinson @nitobuendia Thanks again for all your work on this! Very much appreciated.

**Closed by samdutton** 2018-02-05 10:15 UTC

**Comment by thbaja** [comment] 2018-02-07 11:56
You should probably also update the code samples in the actual guide.
See https://codelabs.developers.google.com/codelabs/webrtc-web/#6

**Comment by samdutton** [comment] 2018-02-07 14:30
@thbaja Thanks for reminding me!

@nitobuendia Could you have a go at this when you get a moment?

**Comment by samdutton** [comment] 2018-02-21 09:40
@thbaja @nitobuendia Thank you!

I've published the changes to codelab text.
