### ISSUE TITLE
step-02 only works in firefox

### ISSUE THREAD

**Issue by jarmstrong2** [googlecodelabs/webrtc-web#40] opened 2017-08-16 01:36 UTC
[log.txt](https://github.com/googlecodelabs/webrtc-web/files/1226827/log.txt)
Hi, not sure what's going on here, but step 2 only works in firefox for me.

**Comment by jarmstrong2** [comment] 2017-08-24 16:37
fyi this is whats happening in chrome: https://bugs.chromium.org/p/webrtc/issues/detail?id=4483

any workarounds?

**Comment by jarmstrong2** [comment] 2017-08-24 16:43
similar: https://github.com/webrtc/samples/issues/795

**Comment by nitobuendia** [comment] 2017-11-28 13:47
I am unable to reproduce this. I am running macOS Sierra 10.13.1 and Chrome 62.0.3202.94

@jarmstrong2 Is this fixed now? If not, could you provide OS version, browser version and steps to reproduce? Thank you!

**Comment by samdutton** [comment] 2017-12-13 14:28
Hi @jarmstrong2 — thanks for filling the issue, and apologies for the delay in responding. 

As per @nitobuendia's comments, I'll close this, but feel free to open again if you experience problems.

**Closed by samdutton** 2017-12-13 14:28 UTC
