### ISSUE TITLE
Error step-04 folder

### ISSUE THREAD

**Issue by hermanfransen** [googlecodelabs/webrtc-web#47] opened 2017-10-29 14:35 UTC
I have read and done all chapters without any problems. But I get an error while doing: "7. Set up a signaling service to exchange messages". I use `git clone` to get the code on my localhost. I delete the `work` directory and rename the `step-04` folder to `work`. I go inside the `work` folder. I do a `npm install`. Then `node index.js`. It's running without a response, so that's fine. From my browser, I open `localhost:8080` (like it is said). The browser gives error: `ERR_CONNECTION_REFUSED`. In the node console I get the following error message:

```
/Users/My_Name/Localhost/webrtc-googlecodelabs/work/node_modules/node-static/lib/node-static.js:348
                      mime.lookup(files[0]) ||
                           ^
TypeError: mime.lookup is not a function
    at Server.respond (/Users/My_Name/Localhost/webrtc-googlecodelabs/work/node_modules/node-static/lib/node-static.js:348:28)
    at /Users/My_Name/Localhost/webrtc-googlecodelabs/work/node_modules/node-static/lib/node-static.js:64:22
    at FSReqWrap.oncomplete (fs.js:123:15)

```
The same error I get with `step-05` and `step-06`.

I have Node v6.10.2 and Chrome 62.

What am I doing wrong?

**Comment by hermanfransen** [comment] 2017-10-31 12:45
I found a solution myself. I edited the `index.js` like this:

```
'use strict';
var os = require('os');
var app = require('express');
var http = require('http').Server(app);
var io = require('socket.io')(http);
var port = process.env.Port || 3000;
io.sockets.on('connection', function(socket) {
  // no changes, same as original
});
http.listen(port, function(){
  console.log('listening on *:' + port);
})
```
Install `express` with the command `npm install express --save`

And in the `index.html` change the line:  
`<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>`

Since `index.html` is not served anymore by the node app 'index.js` (by the changes I made), I have  installed the 'Webserver for Chrome' that is a webserver now for `index.html`.

**Comment by quangtrung89** [comment] 2017-11-17 13:51
I cannot get it work, and same issue! I tried with @hermanfransen suggest, but not help at all.

**Comment by nitobuendia** [comment] 2017-11-28 12:40
I can reproduce the error. It seems that updating node-static dependency makes it work.
Credit: https://stackoverflow.com/a/46622619/7684576

Submitting PR.

**Comment by nitobuendia** [comment] 2017-11-28 13:05
Problem seems to be reproducible in steps 5 and 6 too. Submitting PR for them too.

**Comment by samdutton** [comment] 2017-12-11 13:31
Thanks @hermanfransen and @quangtrung89 ! 

Apologies for the delay in responding. 

Should be fixed as @nitobuendia describes.

**Closed by samdutton** 2017-12-11 13:31 UTC
