### ISSUE TITLE
Step 05

### ISSUE THREAD

**Issue by YuriyPomaznoy** [googlecodelabs/webrtc-web#39] opened 2017-08-11 19:07 UTC
In the file main.js the function handleRemoteStreamAdd is declared twice. 
In the file index.js: `var numClients = io.sockets.sockets.length;` - variable numClients = undefined
Probably should be `Object.keys(io.sockets.sockets).length`

**Comment by nitobuendia** [comment] 2017-11-28 11:27
Hello @YuriyPomaznoy, I understand both of these comments are referring to step 5. Is that correct?

For now, I was able to identify the duplicated "handleRemoteStreamAdded(event)" function and submitted a PR.

**Comment by nitobuendia** [comment] 2017-11-28 11:51
On a second look, this looks duplicate of #3 and #5 respectively. Do you agree, @YuriyPomaznoy ?

**Comment by YuriyPomaznoy** [comment] 2017-11-29 04:24
To step 7, line 31:
`var numClients = io.sockets.sockets.length;`
Should be:
`var numClients = Object.keys(io.sockets.sockets).length;`

**Comment by YuriyPomaznoy** [comment] 2017-11-29 04:26
To step 7, line 31:
var numClients = io.sockets.sockets.length;
Should be:
var numClients = Object.keys(io.sockets.sockets).length;

2017-11-28 18:51 GMT+07:00 Nito Buendia <notifications@github.com>:

**Comment by YuriyPomaznoy** [comment] 2017-11-29 04:58
Correct step 7, completely (sorry for my bad english)
```
var os = require('os');
var nodeStatic = require('node-static');
var http = require('http');
var socketIO = require('socket.io');

var fileServer = new(nodeStatic.Server)();
var app = http.createServer(function(req, res) {
  fileServer.serve(req, res);
}).listen(8080);

var io = socketIO.listen(app);

	var clientsArray = {};
	var roomNow;

io.sockets.on('connection', function(socket) {

	// convenience function to log server messages on the client
	function log() {
		var array = ['Message from server:'];
		array.push.apply(array, arguments);
		socket.emit('log', array);
	}

	socket.on('message', function(message) {
		
		io.sockets.in(roomNow).emit('message', message);

	});

	socket.on('create or join', function(room) {

		roomNow = room;

		if(clientsArray[room] === undefined)
			clientsArray[room] = [];
		clientsArray[room].push(socket.id);

		log('Received request to create or join room ' + room);

							console.log(clientsArray);

		//var numClients = Object.keys(io.sockets.sockets).length;
		var numClients = clientsArray[room].length;
		log('Room ' + room + ' now has ' + numClients + ' client(s)');

		if (numClients === 1) {
			socket.join(room);
			log('Client ID ' + socket.id + ' created room ' + room);
			io.sockets.in(room).emit('created', room, socket.id);
		} else if (numClients === 2) {
			log('Client ID ' + socket.id + ' joined room ' + room);
			io.sockets.in(room).emit('join', room);
			socket.join(room);
			io.sockets.in(room).emit('joined', room, socket.id);
		} else { // max two clients
			socket.emit('full', room);
		}
	});

	socket.on('disconnect', function() {
		for(var key in clientsArray) {
			for(var i=0; i<clientsArray[key].length; i++) {
				if(clientsArray[key][i] == socket.id) {
					clientsArray[key].splice(i, 1);
				}
			}
		}
	});

	socket.on('ipaddr', function() {
		var ifaces = os.networkInterfaces();
		for (var dev in ifaces) {
			ifaces[dev].forEach(function(details) {
				if (details.family === 'IPv4' && details.address !== '127.0.0.1') {
					socket.emit('ipaddr', details.address);
				}
			});
		}
	});

});
```

**Comment by samdutton** [comment] 2017-12-13 14:16
Hi @YuriyPomaznoy — thanks for the heads-up, and apologies for the delay in responding.

I'll close this, given the comments from @nitobuendia, and we'll do a separate PR for the `numCllients` stuff.

**Comment by nitobuendia** [comment] 2017-12-13 14:18
To complete here: we will follow up that issue on #5. Thanks again :)

**Comment by samdutton** [comment] 2017-12-13 14:21
OK — reopened :).

**Comment by samdutton** [comment] 2017-12-13 14:26
...and now closed :).

**Closed by samdutton** 2017-12-13 14:26 UTC

**Comment by sarathkumar654** [comment] 2018-04-26 03:42
I uesd this code in step 5 var os = require('os');
var nodeStatic = require('node-static');
var http = require('http');
var socketIO = require('socket.io');

var fileServer = new(nodeStatic.Server)();
var app = http.createServer(function(req, res) {
  fileServer.serve(req, res);
}).listen(8080);

var io = socketIO.listen(app);

	var clientsArray = {};
	var roomNow;

io.sockets.on('connection', function(socket) {

	// convenience function to log server messages on the client
	function log() {
		var array = ['Message from server:'];
		array.push.apply(array, arguments);
		socket.emit('log', array);
	}

	socket.on('message', function(message) {
		
		io.sockets.in(roomNow).emit('message', message);

	});

	socket.on('create or join', function(room) {

		roomNow = room;

		if(clientsArray[room] === undefined)
			clientsArray[room] = [];
		clientsArray[room].push(socket.id);

		log('Received request to create or join room ' + room);

							console.log(clientsArray);

		//var numClients = Object.keys(io.sockets.sockets).length;
		var numClients = clientsArray[room].length;
		log('Room ' + room + ' now has ' + numClients + ' client(s)');

		if (numClients === 1) {
			socket.join(room);
			log('Client ID ' + socket.id + ' created room ' + room);
			io.sockets.in(room).emit('created', room, socket.id);
		} else if (numClients === 2) {
			log('Client ID ' + socket.id + ' joined room ' + room);
			io.sockets.in(room).emit('join', room);
			socket.join(room);
			io.sockets.in(room).emit('joined', room, socket.id);
		} else { // max two clients
			socket.emit('full', room);
		}
	});

	socket.on('disconnect', function() {
		for(var key in clientsArray) {
			for(var i=0; i<clientsArray[key].length; i++) {
				if(clientsArray[key][i] == socket.id) {
					clientsArray[key].splice(i, 1);
				}
			}
		}
	});

	socket.on('ipaddr', function() {
		var ifaces = os.networkInterfaces();
		for (var dev in ifaces) {
			ifaces[dev].forEach(function(details) {
				if (details.family === 'IPv4' && details.address !== '127.0.0.1') {
					socket.emit('ipaddr', details.address);
				}
			});
		}
	});

});
but I disconnect a room all the room  calls are disconnecting

**Comment by YuriyPomaznoy** [comment] 2018-04-26 05:05
This is a simple, instructional example. In the original it was so that you had to restart the server every time. I just fixed it. For complex cases - https://play.google.com/store/apps/details?id=rmc3.videoconference

**Comment by sarathkumar654** [comment] 2018-04-26 06:47
Can you provide the code to restart the server

**Comment by sarathkumar654** [comment] 2018-04-26 07:03
I am facing a problem with the above code A&B, C&D, E&F can communicate each other at a time but A&B closes connection all other room connections are disconnected , simply if any room connection will close other rooms are automatically disconnected. how to rectify this problem anybody provide some sample code for this

**Comment by YuriyPomaznoy** [comment] 2018-04-27 18:47
Empty the room after the first disconnect from it
```
socket.on('disconnect', function() {
	for(var key in clientsArray) {
		for(var i=0; i<clientsArray[key].length; i++) {
			if(clientsArray[key][i] == socket.id) {
				clientsArray[key] = [];
			}
		}
	}
});
```
or delete it from the object
```
socket.on('disconnect', function() {
	for(var key in clientsArray) {
		for(var i=0; i<clientsArray[key].length; i++) {
			if(clientsArray[key][i] == socket.id) {
				delete clientsArray[key];
			}
		}
	}
});
```

**Comment by YuriyPomaznoy** [comment] 2018-04-28 18:31
ha-ha!
```
function hangup() {
  console.log('Hanging up.');
  stop();
  // sendMessage('bye');		On the client, do not send this message
}
```

**Comment by sarathkumar654** [comment] 2018-04-30 06:03
still all the rooms are get disconnected while I close a video call 
I used this code 
function hangup() {
  console.log('Hanging up.');
  stop();
  // sendMessage('bye');		On the client, do not send this message
}
but it is not working

**Comment by YuriyPomaznoy** [comment] 2018-04-30 07:11
All the client code is from me
```
'use strict';

var isChannelReady = false;
var isInitiator = false;
var isStarted = false;
var localStream;
var pc;
var remoteStream;
var turnReady;

var pcConfig = {
  'iceServers': [{
    'urls': 'stun:stun.l.google.com:19302'
  }]
};

// Set up audio and video regardless of what devices are present.
var sdpConstraints = {
  offerToReceiveAudio: true,
  offerToReceiveVideo: true
};

/////////////////////////////////////////////

// Could prompt for room name:
//var room = prompt('Enter room name:', 'foo-bar');
/////////////////// ?????????????????????????????????
var socket = io.connect('http://localhost:3001');

if (room !== '') {
  socket.emit('create or join', room);
  console.log('Attempted to create or  join room', room);
}

socket.on('created', function(room) {
  console.log('Created room ' + room);
  isInitiator = true;
});

socket.on('full', function(room) {
  alert('Room ' + room + ' is full');
});

socket.on('join', function (room){
  console.log('Another peer made a request to join room ' + room);
  console.log('This peer is the initiator of room ' + room + '!');
  isChannelReady = true;
});

socket.on('joined', function(room) {
  console.log('joined: ' + room);
  isChannelReady = true;
});

socket.on('log', function(array) {
  console.log.apply(console, array);
});

////////////////////////////////////////////////

function sendMessage(message) {
  console.log('Client sending message: ', message);
  socket.emit('message', message);
}

// This client receives a message
socket.on('message', function(message) {
  console.log('Client received message:', message);
  if (message === 'got user media') {
    maybeStart();
  } else if (message.type === 'offer') {
    if (!isInitiator && !isStarted) {
      maybeStart();
    }
    pc.setRemoteDescription(new RTCSessionDescription(message));
    doAnswer();
  } else if (message.type === 'answer' && isStarted) {
    pc.setRemoteDescription(new RTCSessionDescription(message));
  } else if (message.type === 'candidate' && isStarted) {
    var candidate = new RTCIceCandidate({
      sdpMLineIndex: message.label,
      candidate: message.candidate
    });
    pc.addIceCandidate(candidate);
  } else if (message === 'bye' && isStarted) {				///////////////////// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    handleRemoteHangup();
  }
});

////////////////////////////////////////////////////

var localVideo = document.querySelector('#localvideo');
var remoteVideo = document.querySelector('#remotevideo');

navigator.mediaDevices.getUserMedia = navigator.mediaDevices.getUserMedia
  || navigator.mediaDevices.mozGetUserMedia || navigator.mediaDevices.webkitGetUserMedia;

navigator.mediaDevices.getUserMedia({
  audio: true,
  video: true
})
.then(gotStream)
.catch(function(e) {
  alert('getUserMedia() error: ' + e.name);
});

function gotStream(stream) {
  console.log('Adding local stream.');
  // localVideo.src = window.URL.createObjectURL(stream);
	localVideo.srcObject = stream;
  localStream = stream;
  sendMessage('got user media');
  if (isInitiator) {
    maybeStart();
  }
}

var constraints = {
  video: true
};

console.log('Getting user media with constraints', constraints);

if (location.hostname !== 'localhost') {
  requestTurn(
    'https://computeengineondemand.appspot.com/turn?username=41784574&key=4080218913'
  );
}

function maybeStart() {
  console.log('>>>>>>> maybeStart() ', isStarted, localStream, isChannelReady);
  if (!isStarted && typeof localStream !== 'undefined' && isChannelReady) {
    console.log('>>>>>> creating peer connection');
    createPeerConnection();
    pc.addStream(localStream);
    isStarted = true;
    console.log('isInitiator', isInitiator);
    if (isInitiator) {
      doCall();
    }
  }
}

//window.addEventListener('beforeunload', function() {
//  sendMessage('bye');
//});
// window.onbeforeunload = function() {
//     sendMessage('bye');
// };

/////////////////////////////////////////////////////////

function createPeerConnection() {
  try {
    pc = new RTCPeerConnection(null);
    pc.onicecandidate = handleIceCandidate;
    pc.onaddstream = handleRemoteStreamAdded;					/////////// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    pc.onremovestream = handleRemoteStreamRemoved;
    console.log('Created RTCPeerConnnection');
  } catch (e) {
    console.log('Failed to create PeerConnection, exception: ' + e.message);
    alert('Cannot create RTCPeerConnection object.');
    return;
  }
}

function handleIceCandidate(event) {
  console.log('icecandidate event: ', event);
  if (event.candidate) {
    sendMessage({
      type: 'candidate',
      label: event.candidate.sdpMLineIndex,
      id: event.candidate.sdpMid,
      candidate: event.candidate.candidate
    });
  } else {
    console.log('End of candidates.');
  }
}

function handleRemoteStreamAdded(event) {
  console.log('Remote stream added.');
  remoteVideo.srcObject = event.stream;
  remoteStream = event.stream;
}

function handleCreateOfferError(event) {
  console.log('createOffer() error: ', event);
}

function doCall() {
  console.log('Sending offer to peer');
  pc.createOffer(setLocalAndSendMessage, handleCreateOfferError);
}

function doAnswer() {
  console.log('Sending answer to peer.');
  pc.createAnswer().then(
    setLocalAndSendMessage,
    onCreateSessionDescriptionError
  );
}

function setLocalAndSendMessage(sessionDescription) {
  // Set Opus as the preferred codec in SDP if Opus is present.
  //  sessionDescription.sdp = preferOpus(sessionDescription.sdp);
  pc.setLocalDescription(sessionDescription);
  console.log('setLocalAndSendMessage sending message', sessionDescription);
  sendMessage(sessionDescription);
}

function onCreateSessionDescriptionError(error) {
  trace('Failed to create session description: ' + error.toString());
}

function requestTurn(turnURL) {
  var turnExists = false;
  for (var i in pcConfig.iceServers) {
    if (pcConfig.iceServers[i].url.substr(0, 5) === 'turn:') {
      turnExists = true;
      turnReady = true;
      break;
    }
  }
  if (!turnExists) {
    console.log('Getting TURN server from ', turnURL);
    // No TURN server. Get one from computeengineondemand.appspot.com:
    var xhr = new XMLHttpRequest();
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4 && xhr.status === 200) {
        var turnServer = JSON.parse(xhr.responseText);
        console.log('Got TURN server: ', turnServer);
        pcConfig.iceServers.push({
          'url': 'turn:' + turnServer.username + '@' + turnServer.turn,
          'credential': turnServer.password
        });
        turnReady = true;
      }
    };
    xhr.open('GET', turnURL, true);
    xhr.send();
  }
}

//function handleRemoteStreamAdded(event) {
//  console.log('Remote stream added.');
//  remoteVideo.src = window.URL.createObjectURL(event.stream);
//  remoteStream = event.stream;
//}

function handleRemoteStreamRemoved(event) {
  console.log('Remote stream removed. Event: ', event);
}

function hangup() {
  console.log('Hanging up.');
  stop();
  // sendMessage('bye');		On the client, do not send this message
}

function handleRemoteHangup() {
  console.log('Session terminated.');
  stop();
  isInitiator = false;																				//	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}

function stop() {
  isStarted = false;
  // isAudioMuted = false;
  // isVideoMuted = false;
  pc.close();
  pc = null;
}

///////////////////////////////////////////

// Set Opus as the default audio codec if it's present.
function preferOpus(sdp) {
  var sdpLines = sdp.split('\r\n');
  var mLineIndex;
  // Search for m line.
  for (var i = 0; i < sdpLines.length; i++) {
    if (sdpLines[i].search('m=audio') !== -1) {
      mLineIndex = i;
      break;
    }
  }
  if (mLineIndex === null) {
    return sdp;
  }

  // If Opus is available, set it as the default in m line.
  for (i = 0; i < sdpLines.length; i++) {
    if (sdpLines[i].search('opus/48000') !== -1) {
      var opusPayload = extractSdp(sdpLines[i], /:(\d+) opus\/48000/i);
      if (opusPayload) {
        sdpLines[mLineIndex] = setDefaultCodec(sdpLines[mLineIndex],
          opusPayload);
      }
      break;
    }
  }

  // Remove CN in m line and sdp.
  sdpLines = removeCN(sdpLines, mLineIndex);

  sdp = sdpLines.join('\r\n');
  return sdp;
}

function extractSdp(sdpLine, pattern) {
  var result = sdpLine.match(pattern);
  return result && result.length === 2 ? result[1] : null;
}

// Set the selected codec to the first in m line.
function setDefaultCodec(mLine, payload) {
  var elements = mLine.split(' ');
  var newLine = [];
  var index = 0;
  for (var i = 0; i < elements.length; i++) {
    if (index === 3) { // Format of media starts from the fourth.
      newLine[index++] = payload; // Put target payload to the first.
    }
    if (elements[i] !== payload) {
      newLine[index++] = elements[i];
    }
  }
  return newLine.join(' ');
}

// Strip CN from sdp before CN constraints is ready.
function removeCN(sdpLines, mLineIndex) {
  var mLineElements = sdpLines[mLineIndex].split(' ');
  // Scan from end for the convenience of removing an item.
  for (var i = sdpLines.length - 1; i >= 0; i--) {
    var payload = extractSdp(sdpLines[i], /a=rtpmap:(\d+) CN\/\d+/i);
    if (payload) {
      var cnPos = mLineElements.indexOf(payload);
      if (cnPos !== -1) {
        // Remove CN payload from m line.
        mLineElements.splice(cnPos, 1);
      }
      // Remove CN line in sdp
      sdpLines.splice(i, 1);
    }
  }

  sdpLines[mLineIndex] = mLineElements.join(' ');
  return sdpLines;
}
```
All server code
var os = require('os');
var sktio = require('socket.io');

module.exports = function(server) {
	var clientsArray = {};
	var io = sktio(server);
	var roomNow;

io.sockets.on('connection', function(socket) {
	
	// convenience function to log server messages on the client
	function log() {
		var array = ['Message from server:'];
		array.push.apply(array, arguments);
		socket.emit('log', array);
	}

	socket.on('message', function(message) {
		
		// log('Client said: ', message);
		// for a real app, would be room-only (not broadcast)
		// socket.broadcast.emit('message', message);
		io.sockets.in(roomNow).emit('message', message);

	});

	socket.on('create or join', function(room) {

		roomNow = room;

		if(clientsArray[room] === undefined)
			clientsArray[room] = [];
		clientsArray[room].push(socket.id);

		log('Received request to create or join room ' + room);

							console.log(clientsArray);

		//var numClients = Object.keys(io.sockets.sockets).length;
		var numClients = clientsArray[room].length;
		log('Room ' + room + ' now has ' + numClients + ' client(s)');

		if (numClients === 1) {
			socket.join(room);
			log('Client ID ' + socket.id + ' created room ' + room);
			io.sockets.in(room).emit('created', room, socket.id);
			// socket.emit('created', room, socket.id);

		} else if (numClients === 2) {
			log('Client ID ' + socket.id + ' joined room ' + room);
			io.sockets.in(room).emit('join', room);
			socket.join(room);
			io.sockets.in(room).emit('joined', room, socket.id);
			// socket.emit('joined', room, socket.id);
			// io.sockets.in(room).emit('ready');
		} else { // max two clients
			socket.emit('full', room);
		}
	});
	socket.on('disconnect', function() {
		for(var key in clientsArray) {
			for(var i=0; i<clientsArray[key].length; i++) {
				if(clientsArray[key][i] == socket.id) {
					clientsArray[key].splice(i, 1);
				}
			}
		}
					console.log(clientsArray);
	});

	socket.on('ipaddr', function() {
		var ifaces = os.networkInterfaces();
		for (var dev in ifaces) {
			ifaces[dev].forEach(function(details) {
				if (details.family === 'IPv4' && details.address !== '127.0.0.1') {
					// socket.emit('ipaddr', '127.0.0.1');
					socket.emit('ipaddr', details.address);
				}
			});
		}
	});

});

};

**Comment by YuriyPomaznoy** [comment] 2018-04-30 07:14
Everything is working
```
GET / 200 4070.844 ms
GET /go-rtc 304 123.064 ms
{ foo: [ 'IvGx_pUBmFwvaRaJAAAA' ] }
GET /go-rtc 304 126.898 ms
{ foo: [ 'IvGx_pUBmFwvaRaJAAAA' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB' ] }
GET /go-rtc 304 105.445 ms
{ foo: [ 'IvGx_pUBmFwvaRaJAAAA', 't9EnR3uSYxjZMM-oAAAC' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB' ] }
GET /go-rtc 304 194.731 ms
{ foo: [ 'IvGx_pUBmFwvaRaJAAAA', 't9EnR3uSYxjZMM-oAAAC' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB', '2NQKCi0AbLig375zAAAD' ] }
{ foo: [ 't9EnR3uSYxjZMM-oAAAC' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB', '2NQKCi0AbLig375zAAAD' ] }
GET /go-rtc 304 100.887 ms
{ foo: [ 't9EnR3uSYxjZMM-oAAAC', 'altqfw_cZPbbYBLfAAAE' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB', '2NQKCi0AbLig375zAAAD' ] }
{ foo: [ 't9EnR3uSYxjZMM-oAAAC' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB', '2NQKCi0AbLig375zAAAD' ] }
{ foo: [],
  bar: [ 'NlCjlR0MhavPgmKoAAAB', '2NQKCi0AbLig375zAAAD' ] }
GET /go-rtc 304 119.343 ms
{ foo: [ 'EWjfAMdPaWDghbN9AAAF' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB', '2NQKCi0AbLig375zAAAD' ] }
GET /go-rtc 304 102.493 ms
{ foo: [ 'EWjfAMdPaWDghbN9AAAF', 'dxLS4aJO18xS68hLAAAG' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB', '2NQKCi0AbLig375zAAAD' ] }
{ foo: [ 'EWjfAMdPaWDghbN9AAAF', 'dxLS4aJO18xS68hLAAAG' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB' ] }
GET /go-rtc 304 87.981 ms
{ foo: [ 'EWjfAMdPaWDghbN9AAAF', 'dxLS4aJO18xS68hLAAAG' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB' ],
  baz: [ 'LEHKjgaHsCxoolH4AAAH' ] }
GET /go-rtc 304 76.438 ms
{ foo: [ 'EWjfAMdPaWDghbN9AAAF', 'dxLS4aJO18xS68hLAAAG' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB' ],
  baz: [ 'LEHKjgaHsCxoolH4AAAH', '5iRQZr51BkYM8-4XAAAI' ] }
{ foo: [ 'EWjfAMdPaWDghbN9AAAF' ],
  bar: [ 'NlCjlR0MhavPgmKoAAAB' ],
  baz: [ 'LEHKjgaHsCxoolH4AAAH', '5iRQZr51BkYM8-4XAAAI' ] }
{ foo: [],
  bar: [ 'NlCjlR0MhavPgmKoAAAB' ],
  baz: [ 'LEHKjgaHsCxoolH4AAAH', '5iRQZr51BkYM8-4XAAAI' ] }
{ foo: [],
  bar: [],
  baz: [ 'LEHKjgaHsCxoolH4AAAH', '5iRQZr51BkYM8-4XAAAI' ] }
GET /go-rtc 304 213.221 ms
GET /go-rtc 304 107.315 ms
GET /go-rtc 304 113.495 ms
GET /go-rtc 304 118.767 ms
{ foo: [ '4E2Fc4Ip8HXoKHVTAAAJ' ],
  bar: [],
  baz: [ 'LEHKjgaHsCxoolH4AAAH', '5iRQZr51BkYM8-4XAAAI' ] }
GET /go-rtc 304 125.519 ms
{ foo: [ '4E2Fc4Ip8HXoKHVTAAAJ', '5EPsj1V8F9g3nwFzAAAK' ],
  bar: [],
  baz: [ 'LEHKjgaHsCxoolH4AAAH', '5iRQZr51BkYM8-4XAAAI' ] }
{ foo: [ '4E2Fc4Ip8HXoKHVTAAAJ', '5EPsj1V8F9g3nwFzAAAK' ],
  bar: [],
  baz: [ 'LEHKjgaHsCxoolH4AAAH' ] }
{ foo: [ '4E2Fc4Ip8HXoKHVTAAAJ', '5EPsj1V8F9g3nwFzAAAK' ],
  bar: [],
  baz: [] }
{ foo: [ '4E2Fc4Ip8HXoKHVTAAAJ' ], bar: [], baz: [] }
{ foo: [], bar: [], baz: [] }
```

**Comment by YuriyPomaznoy** [comment] 2018-04-30 07:36
Do you see the logs?
One room, the second room, disconnected in the first room, again disconnected in the first room, again turned up in the first room, a third room appeared, etc. etc.
Everything is working.

**Comment by sarathkumar654** [comment] 2018-05-02 08:06
thanks for the code ,
we are facing a problem outside networks cant connect to our network , how to rectify this problem.

**Comment by YuriyPomaznoy** [comment] 2018-05-04 15:36
https://github.com/muaz-khan/RTCMultiConnection#v3-demos

**Comment by sarathkumar654** [comment] 2018-05-25 09:22
I tried to add a third person to the  room for step no -5  but its not working, can you help us

**Comment by YuriyPomaznoy** [comment] 2018-05-25 12:01
On the above link there is the item "Video Conferencing". There are ready-made client side and server side codes. I made a video conference on them for any number of clients - they are working codes.
This training example can not be expanded.

**Comment by sarathkumar654** [comment] 2018-06-05 07:12
I tried to add a third participant , in server a third participant added  by adding number of clients , but no peer connection created for third person . should I made any changes in main.js page
